stages:
  - test
  - build

variables:
  DOCKER_DRIVER: 'overlay2'
  DOCKER_HOST: 'tcp://docker:2375'

default:
  image:
    name: docker/compose:1.22.0
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - apk add -U make bash git
    - echo "export CUSTOM_HOSTNAME=$(hostname -i docker)" > .env
    - echo "export DOCKER_HOST=$DOCKER_HOST" >> .env
    - adduser -h /home/git -D -u 1000 git
    - chown -R git:git .
  tags:
    - gitlab-org-docker

workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'

.dev:
  script:
    - su git -mc 'make deps'
    - su git -mc 'git -C gitlab-rails checkout $GITLAB_RAILS_BRANCH'
    - su git -mc 'if ! make create-dev; then make logs > logs.txt; exit 1; fi'
  artifacts:
    paths:
      - logs.txt

dev FOSS:
  extends: .dev
  variables:
    GITLAB_RAILS_BRANCH: master-foss

dev CE:
  extends: .dev
  variables:
    GITLAB_RAILS_BRANCH: master
    FOSS_ONLY: 1

dev EE:
  extends: .dev
  variables:
    GITLAB_RAILS_BRANCH: master
  # enabled, because of https://gitlab.com/gitlab-org/gitlab/merge_requests/15556
  allow_failure: true

.test:
  script:
    - su git -mc 'make deps'
    - su git -mc 'git -C gitlab-rails checkout $GITLAB_RAILS_BRANCH'
    - su git -mc 'make create-test'
    - su git -mc 'make command'
  variables:
    COMMAND: bin/rspec spec/models/chat_name_spec.rb

test FOSS:
  extends: .test
  variables:
    GITLAB_RAILS_BRANCH: master-foss

test CE:
  extends: .test
  variables:
    GITLAB_RAILS_BRANCH: master
    FOSS_ONLY: 1

test EE:
  extends: .test
  variables:
    GITLAB_RAILS_BRANCH: master
