image:
  name: docker/compose:1.22.0
  entrypoint: [""]

services:
  - docker:dind

variables:
  DOCKER_DRIVER: 'overlay2'
  DOCKER_HOST: 'tcp://docker:2375'

before_script:
  - apk add -U make bash git
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - export HOST=$(hostname -i docker)

stages:
  - test
  - build

test-dev:
  script:
    - make create-dev

build:
  script:
    - make build
    - make push
