stages:
  - test
  - build

variables:
  DOCKER_DRIVER: 'overlay2'
  DOCKER_HOST: 'tcp://docker:2375'

  # We test by default against 1.21.0 as this the latest version
  # that is part of Debian/Buster and Ubuntu/Bionic
  COMPOSE_VERSION: '1.21.0'

default:
  image:
    name: docker/compose:$COMPOSE_VERSION
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - apk add -U make bash git
    - echo "export CUSTOM_HOSTNAME=$(hostname -i docker)" > gck.env
    - echo "export DOCKER_HOST=$DOCKER_HOST" >> gck.env
    - adduser -h /home/git -D -u 1000 git
    - chown -R git:git .
  tags:
    - gitlab-org-docker

workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'

.logs:
  after_script:
    - su git -mc 'make logs > logs.txt'
  artifacts:
    when: always
    expire_in: 1 month
    paths:
      - logs.txt

.dev:
  script:
    - su git -mc 'make deps'
    - su git -mc 'git -C gitlab-rails checkout $GITLAB_RAILS_BRANCH'
    - su git -mc 'make create-dev'

dev FOSS:
  extends: [.dev, .logs]
  variables:
    GITLAB_RAILS_BRANCH: master-foss

dev CE:
  extends: [.dev, .logs]
  variables:
    GITLAB_RAILS_BRANCH: master
    FOSS_ONLY: 1

dev EE:
  extends: [.dev, .logs]
  variables:
    GITLAB_RAILS_BRANCH: master
  # enabled, because of https://gitlab.com/gitlab-org/gitlab/merge_requests/15556
  allow_failure: true

.test:
  script:
    - su git -mc 'make deps'
    - su git -mc 'git -C gitlab-rails checkout $GITLAB_RAILS_BRANCH'
    - su git -mc 'make create-test'
    - su git -mc 'make command'
  variables:
    COMMAND: bin/rspec spec/models/chat_name_spec.rb spec/features/issues/gfm_autocomplete_spec.rb:27

test FOSS:
  extends: [.test, .logs]
  variables:
    GITLAB_RAILS_BRANCH: master-foss

test CE:
  extends: [.test, .logs]
  variables:
    GITLAB_RAILS_BRANCH: master
    FOSS_ONLY: 1

test EE:
  extends: [.test, .logs]
  variables:
    GITLAB_RAILS_BRANCH: master

bats unit tests:
  script:
    - apk add -U bats
    - su git -mc 'bats bats/'

.smoke_test:
  script:
    - echo 'export USE_WEBPACK_DEV=false' >> gck.env
    - su git -mc 'make up-pgadmin'

smoke-test compose:1.21:
  extends: .smoke_test
  variables:
    COMPOSE_VERSION: '1.21.0'

smoke-test compose:1.25:
  extends: .smoke_test
  variables:
    COMPOSE_VERSION: '1.25.0'
