image:
  name: docker/compose:1.22.0
  entrypoint: [""]

services:
  - docker:dind

variables:
  DOCKER_DRIVER: 'overlay2'
  DOCKER_HOST: 'tcp://docker:2375'

before_script:
  - apk add -U make
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - test
  - build

build:
  script:
    - make build
    - make push
