version: '2.1'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    expose:
      - 5775/udp # UDP: agent: accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - 6831/udp # UDP: agent: accept jaeger.thrift over compact thrift protocol
      - 6832/udp # UDP: agent: accept jaeger.thrift over binary thrift protocol
      - 5778/tcp # HTTP: agent: serve configs
      - 14268/tcp # HTTP: collector: accept jaeger.thrift directly from clients
      - 9411/tcp # HTTP: collector: Zipkin compatible endpoint (optional)
    ports:
      - 16686:16686/tcp # HTTP: query: serve frontend
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  pgadmin:
    image: registry.gitlab.com/ayufan/gitlab-compose-kit/releases:pgadmin-${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles/pgadmin
    expose:
      - 8080
    ports:
      - 9092:8080/tcp
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gck@gck
      PGADMIN_DEFAULT_PASSWORD: gck
      PGADMIN_LISTEN_PORT: 8080
    restart: on-failure:1

volumes:
  pgadmin:
