version: '2'
services:
  unicorn:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-rails:/home/git/gitlab
    expose:
      - 8080
    depends_on:
      - gitaly
      - redis
    command: [/scripts/unicorn.sh]

  workhorse:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-shell:/home/git/gitlab-shell
      - ./gitlab-workhorse:/home/git/gitlab-workhorse
    expose:
      - 8181
    depends_on:
      - gitaly
      - redis
    command: [/scripts/workhorse.sh]

  webpack:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-rails:/home/git/gitlab
    environment:
      DEV_SERVER_PORT: 3808
      DEV_SERVER_HOST: 0.0.0.0
      DEV_SERVER_LIVERELOAD: 'true'
    expose:
      - 3808
    command: [/scripts/webpack.sh]

  gitaly:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitaly:/home/git/gitaly
      - ./gitlab-shell:/home/git/gitlab-shell
    depends_on:
      - redis
    expose:
      - 9999
    command: [/scripts/gitaly.sh]

  postgres:
    image: 'sameersbn/postgresql:9.4-20'
    restart: always
    environment:
    - DB_NAME=gitlabhq_production
    - DB_PASS=2F0nT6nR5a0860f
    - DB_USER=gitlab
    - DB_EXTENSION=pg_trgm
    volumes:
    - 'postgres:/var/lib/postgresql'
    mem_limit: 256M

  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
    - 'redis:/var/lib/redis'
    expose:
    - 6379
    mem_limit: 128M

volumes:
  redis:
  postgres:
