version: '2.1'

services:
  pgadmin:
    image: registry.gitlab.com/ayufan/gitlab-compose-kit/releases:pgadmin-${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles/pgadmin
    expose:
      - 8080
    ports:
      - 8080
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gck@gck
      PGADMIN_DEFAULT_PASSWORD: gck
      PGADMIN_LISTEN_PORT: 8080
    restart: on-failure:1

volumes:
  pgadmin:
