version: '2'
services:
  unicorn:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
    volumes:
      - ./data:/home/git:delegated
      - ./gitlab-shell:/home/git/gitlab-shell:cached
      - ./gitlab-rails:/home/git/gitlab:cached
      - ./gitaly:/home/git/gitaly:cached
      - cache:/data/cache
      - repositories:/data/repositories
      - shared:/data/shared
    expose:
      - 8080
    depends_on:
      - postgres
      - redis
      - gitaly
      - webpack
      - minio
    environment:
      RAILS_ENV: development
      GITLAB_RAILS_REVISION: ${GITLAB_RAILS_REVISION}
      GITLAB_SHELL_REVISION: ${GITLAB_SHELL_REVISION}
      USE_RAILS_SERVER: ${USE_RAILS_SERVER}
      USE_RAILS5: ${USE_RAILS5}
      HOST: ${HOST}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG}
    working_dir: /home/git/gitlab
    entrypoint: [/usr/local/bin/dumb-init, --, /scripts/entrypoint/gitlab-rails-env.sh]
    command: [/scripts/startup/unicorn.sh]

  sidekiq:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
    volumes:
      - ./data:/home/git:delegated
      - ./gitlab-shell:/home/git/gitlab-shell:cached
      - ./gitlab-rails:/home/git/gitlab:cached
      - ./gitaly:/home/git/gitaly:cached
      - cache:/data/cache
      - repositories:/data/repositories
      - shared:/data/shared
    depends_on:
      - postgres
      - redis
      - gitaly
      - minio
    environment:
      RAILS_ENV: development
      GITLAB_RAILS_REVISION: ${GITLAB_RAILS_REVISION}
      GITLAB_SHELL_REVISION: ${GITLAB_SHELL_REVISION}
      USE_RAILS5: ${USE_RAILS5}
      HOST: ${HOST}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG}
    working_dir: /home/git/gitlab
    entrypoint: [/usr/local/bin/dumb-init, --, /scripts/entrypoint/gitlab-rails-env.sh]
    command: [/scripts/startup/sidekiq.sh]

  spring:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
    volumes:
      - ./data:/home/git:delegated
      - ./gitlab-shell:/home/git/gitlab-shell:cached
      - ./gitlab-rails:/home/git/gitlab:cached
      - ./gitaly:/home/git/gitaly:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - cache:/data/cache
      - repositories:/data/repositories
      - shared:/data/shared
    depends_on:
      - postgres
      - redis
      - gitaly
      - webpack
      - minio
    environment:
      RAILS_ENV: development
      ENABLE_SPRING: "${ENABLE_SPRING}"
      SPEC_OPTS: "--format documentation"
      GITLAB_RAILS_REVISION: ${GITLAB_RAILS_REVISION}
      GITLAB_SHELL_REVISION: ${GITLAB_SHELL_REVISION}
      USE_RAILS5: ${USE_RAILS5}
      HOST: ${HOST}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG}
      DISPLAY: ${DISPLAY}
      CHROME_HEADLESS: ${CHROME_HEADLESS}
    tty: true
    working_dir: /home/git/gitlab
    entrypoint: [/usr/local/bin/dumb-init, --, /scripts/entrypoint/gitlab-rails-env.sh]
    command: [cat]

  workhorse:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
    environment:
      GITLAB_WORKHORSE_REVISION: ${GITLAB_WORKHORSE_REVISION}
      GITLAB_SHELL_REVISION: ${GITLAB_SHELL_REVISION}
    volumes:
      - ./data:/home/git:delegated
      - ./gitlab-rails:/home/git/gitlab:cached
      - ./gitlab-shell:/home/git/gitlab-shell:cached
      - ./gitlab-workhorse:/home/git/gitlab-workhorse:cached
      - cache:/data/cache
      - repositories:/data/repositories
      - shared:/data/shared
    expose:
      - 8181
    ports:
      - '3000:8181'
    depends_on:
      - gitaly
      - redis
      - unicorn
      - minio
    working_dir: /home/git/gitlab-workhorse
    entrypoint: [/usr/local/bin/dumb-init, --, /scripts/entrypoint/gitlab-shell-env.sh]
    command: [/scripts/startup/workhorse.sh]

  sshd:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
    environment:
      GITLAB_SHELL_REVISION: ${GITLAB_SHELL_REVISION}
    volumes:
      - ./data:/home/git:delegated
      - ./gitlab-shell:/home/git/gitlab-shell:cached
      - repositories:/data/repositories
    expose:
      - 2222
    ports:
      - '2222:2222'
    depends_on:
      - gitaly
      - redis
      - unicorn
    working_dir: /home/git
    entrypoint: [/usr/local/bin/dumb-init, --, /scripts/entrypoint/gitlab-shell-env.sh]
    command: [sudo, /scripts/startup/sshd.sh]

  webpack:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
        COMPOSE_KIT_REVISION: ${COMPOSE_KIT_REVISION}
    volumes:
      - ./data:/home/git:delegated
      - ./gitlab-rails:/home/git/gitlab:cached
      - cache:/data/cache
    environment:
      DEV_SERVER_PORT: 3808
      DEV_SERVER_HOST: 0.0.0.0
      DEV_SERVER_LIVERELOAD: 'true'
      NODE_ENV: development
      GITLAB_RAILS_REVISION: ${GITLAB_RAILS_REVISION}
    expose:
      - 3808
    working_dir: /home/git/gitlab
    entrypoint: [/usr/local/bin/dumb-init, --]
    command: [/scripts/startup/webpack.sh]

  gitaly:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
    volumes:
      - ./data:/home/git:delegated
      - ./gitaly:/home/git/gitaly:cached
      - ./gitlab-rails:/home/git/gitlab:cached
      - ./gitlab-shell:/home/git/gitlab-shell:cached
      - cache:/data/cache
      - repositories:/data/repositories
    depends_on:
      - redis
    expose:
      - 9999
    environment:
      GITLAB_GITALY_REVISION: ${GITLAB_GITALY_REVISION}
      GITLAB_SHELL_REVISION: ${GITLAB_SHELL_REVISION}
    working_dir: /home/git/gitaly
    entrypoint: [/usr/local/bin/dumb-init, --, /scripts/entrypoint/gitlab-shell-env.sh]
    command: [/scripts/startup/gitaly.sh]

  pages:
    image: gitlab-v2:${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
    volumes:
      - ./data:/home/git:delegated
      - ./gitlab-pages:/home/git/go/src/gitlab.com/gitlab-org/gitlab-pages:cached
      - cache:/data/cache
      - shared:/data/shared
    depends_on:
      - redis
    expose:
      - 8989
    ports:
      - 8989
    environment:
      GITLAB_PAGES_REVISION: ${GITLAB_PAGES_REVISION}
    working_dir: /home/git/go/src/gitlab.com/gitlab-org/gitlab-pages
    entrypoint: [/usr/local/bin/dumb-init, --]
    command: [/scripts/startup/pages.sh]

  registry:
    image: registry:2.4.1
    volumes:
      - registry:/registry
      - ./data:/home/git:delegated
    environment:
      REGISTRY_LOG_LEVEL: info
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
      REGISTRY_AUTH_TOKEN_REALM: http://${HOST}:3000/jwt/auth
      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
      REGISTRY_AUTH_TOKEN_ISSUER: gitlab-issuer
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /home/git/registry-auth.crt
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    expose:
      - 5000
    ports:
      - "5000:5000"

  runner:
    image: gitlab/gitlab-runner:alpine
    environment:
      DOCKER_HOST: tcp://dind:2375
      CI_SERVER_URL: http://workhorse:8181/
      CI_SERVER_TOKEN: SHARED_RUNNER_TOKEN
      CLONE_URL: http://${HOST}:3000/
      RUNNER_EXECUTOR: docker
      DOCKER_VOLUMES: '/var/run/docker.sock:/var/run/docker.sock'
      DOCKER_PRIVILEGED: 'true'
    depends_on:
      - dind
    command: [run-single]

  dind:
    image: docker:dind
    volumes:
      - docker:/var/lib/docker
    environment:
      DOCKER_DRIVER: overlay
    privileged: true
    expose:
      - 2375

  postgres:
    image: 'postgres:9-alpine'
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
    - 'postgres:/var/lib/postgresql/data'
    - './dockerfiles/postgres:/docker-entrypoint-initdb.d:ro'
    expose:
    - 5432
    mem_limit: 256M

  redis:
    image: 'redis:alpine'
    volumes:
    - 'redis:/var/lib/redis'
    expose:
    - 6379
    mem_limit: 128M

  minio:
    image: minio/minio
    volumes:
    - object-storage:/export
    expose:
    - 9000
    ports:
    - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: TEST_KEY
      MINIO_SECRET_KEY: TEST_SECRET
    entrypoint: /bin/sh -c
    command:
      - "mkdir -p /export/artifacts-bucket /export/lfs-bucket /export/uploads-bucket && minio server /export"

volumes:
  redis:
  postgres:
  registry:
  docker:
  cache:
  shared:
  repositories:
  object-storage:
