# This provides a baseline configuration for most of services

version: '2.2'

services:
  web: &application_image
    image: &imagename registry.gitlab.com/gitlab-org/gitlab-compose-kit/releases:${COMPOSE_KIT_REVISION}
    build: &imagebuild
      context: ./dockerfiles
      args:
        UID: ${CUSTOM_UID}
        GID: ${CUSTOM_GID}
        BASE_IMAGE: ${BASE_IMAGE_REPOSITORY}:${BASE_IMAGE_TAG}
        ADDITIONAL_DEPS: ${ADDITIONAL_DEPS}
    volumes:
      - home_git:/home/git
      - src_gck:/gck
      - src_gitlab_shell:/home/git/gitlab-shell
      - src_gitlab_rails:/home/git/gitlab
      - src_gitaly:/home/git/gitaly
      - src_gitlab_metrics_exporter:/home/git/gitlab-metrics-exporter
      - repositories:/data/repositories
      - cache:/data/cache
      - shared:/data/shared
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_HOSTS: "" # undefined
      GITLAB_RAILS_REVISION: ${GITLAB_RAILS_REVISION}
      GITLAB_SHELL_REVISION: ${GITLAB_SHELL_REVISION}
      GITLAB_METRICS_EXPORTER_REVISION: ${GITLAB_METRICS_EXPORTER_REVISION}
      GITLAB_ENABLE_CHAOS_ENDPOINTS: 1 # https://gitlab.com/gitlab-org/gitlab/blob/master/doc/development/chaos_endpoints.md
      GITLAB_CHAOS_SECRET: secret
      CUSTOM_CONFIG: ${CUSTOM_CONFIG}
      CUSTOM_ENV: ${CUSTOM_ENV}
      ENABLE_RBTRACE: "1"
    working_dir: /home/git/gitlab
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 1024
        hard: 16384
    cap_add:
      - SYS_PTRACE
    entrypoint: [/usr/bin/dumb-init, --, /scripts/entrypoint/gitlab-rails-env.sh]

  sidekiq: *application_image
  spring: *application_image
  
  workhorse: &generic_image
    image: *imagename
    build: *imagebuild
    environment:
      CUSTOM_CONFIG: ${CUSTOM_CONFIG}
      CUSTOM_ENV: ${CUSTOM_ENV}
    volumes:
      - home_git:/home/git
      - cache:/data/cache
    entrypoint: [/usr/bin/dumb-init, --, /scripts/entrypoint/gitlab-shell-env.sh]
    restart: on-failure:1

  webpack: *generic_image
  gitaly: *generic_image
  praefect: *generic_image
  pages: *generic_image
  sshd: *generic_image
