version: '2.1'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  pgadmin:
    image: registry.gitlab.com/ayufan/gitlab-compose-kit/releases:pgadmin-${COMPOSE_KIT_REVISION}
    build:
      context: ./dockerfiles/pgadmin
    expose:
      - 8080
    ports:
      - 9092:8080/tcp
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gck@gck
      PGADMIN_DEFAULT_PASSWORD: gck
      PGADMIN_LISTEN_PORT: 8080
    restart: on-failure:1

volumes:
  pgadmin:
