version: '2'
services:
  unicorn:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-shell:/home/git/gitlab-shell
      - ./gitlab-rails:/home/git/gitlab
    expose:
      - 8080
    depends_on:
      - postgres
      - redis
      - gitaly
      - webpack
    environment:
      RAILS_ENV: development
      ENABLE_SPRING: "1"
    working_dir: /home/git/gitlab
    entrypoint: [/scripts/gitlab-rails-env.sh]
    command: [/scripts/unicorn.sh]

  sidekiq:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-shell:/home/git/gitlab-shell
      - ./gitlab-rails:/home/git/gitlab
    depends_on:
      - postgres
      - redis
      - gitaly
    environment:
      RAILS_ENV: development
      ENABLE_SPRING: "1"
    working_dir: /home/git/gitlab
    entrypoint: [/scripts/gitlab-rails-env.sh]
    command: [/scripts/sidekiq.sh]

  workhorse:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-shell:/home/git/gitlab-shell
      - ./gitlab-workhorse:/home/git/gitlab-workhorse
    expose:
      - 8181
    ports:
      - '3000:8181'
    depends_on:
      - gitaly
      - redis
      - unicorn
    working_dir: /home/git/gitlab-workhorse
    command: [/scripts/workhorse.sh]

  sshd:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-shell:/home/git/gitlab-shell
    expose:
      - 2222
    ports:
      - '2222:2222'
    depends_on:
      - gitaly
      - redis
      - unicorn
    working_dir: /home/git
    user: root
    command: [/scripts/sshd.sh]

  webpack:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-rails:/home/git/gitlab
    environment:
      DEV_SERVER_PORT: 3808
      DEV_SERVER_HOST: 0.0.0.0
      DEV_SERVER_LIVERELOAD: 'true'
      NODE_ENV: development
    expose:
      - 3808
    working_dir: /home/git/gitlab
    command: [/scripts/webpack.sh]

  gitaly:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitaly:/home/git/gitaly
      - ./gitlab-shell:/home/git/gitlab-shell
    depends_on:
      - redis
    expose:
      - 9999
    working_dir: /home/git/gitaly
    command: [/scripts/gitaly.sh]

  pages:
    image: gitlab-v2
    volumes:
      - ./data:/home/git
      - ./gitlab-pages:/home/git/go/src/gitlab.com/gitlab-org/gitlab-pages
      - ./gitlab-rails/shared/pages:/home/git/gitlab/shared/pages
    depends_on:
      - redis
    expose:
      - 8989
    ports:
      - 8989
    working_dir: /home/git/go/src/gitlab.com/gitlab-org/gitlab-pages
    command: [/scripts/gitlab-pages.sh]

  registry:
    image: registry:2.4.1
    volumes:
      - registry:/registry
      - ./data:/home/git
    environment:
      REGISTRY_LOG_LEVEL: info
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
      REGISTRY_AUTH_TOKEN_REALM: http://localhost:3000/jwt/auth
      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
      REGISTRY_AUTH_TOKEN_ISSUER: gitlab-issuer
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /home/git/registry-auth.crt
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    expose:
      - 5000
    ports:
      - "5000:5000"

  postgres:
    image: 'postgres:9-alpine'
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
    - 'postgres:/var/lib/postgresql'
    - './dockerfiles/postgres:/docker-entrypoint-initdb.d:ro'
    expose:
    - 5432
    mem_limit: 256M

  redis:
    image: 'redis:alpine'
    volumes:
    - 'redis:/var/lib/redis'
    expose:
    - 6379
    mem_limit: 128M

volumes:
  redis:
  postgres:
  registry:
